/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 plant.gltf --transform
Author: AtskaHeart (https://sketchfab.com/atskaheart)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pixel-flower-pot-f80e4241bebe4a00ad57b0fb8d89b671
Title: Pixel Flower Pot
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/plant-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.MainText}
        position={[0, 0.7, 0]}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.MainText}
        position={[0.07, 1.61, -0.02]}
        rotation={[1.64, 0, 0]}
        scale={0.41}
      />
    </group>
  );
}

useGLTF.preload("/plant-transformed.glb");
